### ISSUE TITLE
Integrate with OpenSim

### ISSUE THREAD

**Issue by malishav** [openwsn-berkeley/openbenchmark#78]
This issue aims at integrating the OpenBenchmark platform with the --runSim option of the OpenVisualizer. This will allow OpenBenchmark to orchestrate and measure the performance of the firmware while in emulated mode.

**Comment by bozidars27** [comment]
Reopened in order to complete the integration with provisioner, common entry-point and GUI

**Comment by bozidars27** [comment]
Reopened in order to complete the integration with provisioner, common entry-point and GUI
